### PR TITLE
Princeisrael improve genesis

### PR DESCRIPTION
**Pull request by Princeadxisrael**
### **The code has been optimized as follows:**

1. Elimination of repeated conditional checks for each flag which violates the D.R.Y principle and has more potential for errors if changes are required.
2. A centralized environment for assigning environment variables using a `flagMappings` map that links each key to the corresponding` GenesisFlags` field.
3. A single loop implemented to set environment variables
4. File-based efficient log shipping with levels. Logs once per environment variable.
5. Error warnings to track incomplete configurations without raising critical errors that might interrupt execution or operators experience

### Further recommendations:

1. Adding structured logging with severity levels in JSON using logrus
2. Collect logs centrally
3. `defer file.Close() `after error check in `init()` function
4. Write unit tests

### CODE REVIEW

**Comment by alexanderguy** [comment]
Hey @Princeadxisrael thanks for the PR!  We're working on some API changes that will make some of this environment setup cleaner, so this is a perfect time to get involved in that.  I'll @ you as soon as that's up.

As far as logging, we're adding support for things like streaming the output from remote executions into the caller (e.g. so it can be shown in the pulumi console).  Rather than logging to a file, how would you see getting that log info some arbitrary stream (e.g. a channel) that users of `svmkit` could consume?

**Comment by Princeadxisrael** [comment]
Okay sounds good.  we may have to initialize a distributed stream processing system? or a remote storage system-

**Comment by alexanderguy** [comment]
> We're working on some API changes that will make some of this environment setup cleaner, so this is a perfect time to get involved in that. I'll @ you as soon as that's up.

hey @Princeadxisrael here's the API I'm about to merge in.  I need to change the naming slightly, but it's close: 

https://github.com/abklabs/svmkit/blob/kit-83-create-a-shell-environment-variable-builder-similar-to-the/pkg/solana/genesis.go#L35

How does that look to you?

> we may have to initialize a distributed stream processing system?

I'm thinking we produce some thing that can be used as a reader, and then hook it up in `pulumi-svmkit` using something like this https://github.com/pulumi/pulumi-command/blob/master/provider/pkg/provider/util/util.go#L32

**Comment by alexanderguy** [comment]
I pushed up the updated code here @Princeadxisrael it's in this PR: https://github.com/abklabs/svmkit/pull/95/commits/e2bcfb9d80a1c83493ad4ed9ecabdca776e6a578#diff-8965594c67306e222c6e240e92571967751423f139181cd0ad3d12f4a844bda7R51

**Comment by Princeadxisrael** [comment]
> > We're working on some API changes that will make some of this environment setup cleaner, so this is a perfect time to get involved in that. I'll @ you as soon as that's up.
> 
> hey @Princeadxisrael here's the API I'm about to merge in. I need to change the naming slightly, but it's close:
> 
> https://github.com/abklabs/svmkit/blob/kit-83-create-a-shell-environment-variable-builder-similar-to-the/pkg/solana/genesis.go#L35
> 
> How does that look to you?

Hey @alexanderguy  I get a 404 error trying to access this API

**Comment by Princeadxisrael** [comment]
Interesting concept. I do not see the logging/severity mechanism. Is that coming from shellquote as well?

**Comment by alexanderguy** [comment]
We haven't added in logging/severity over SSH into pulumi yet, but that's coming soon.

> I'm thinking we produce some thing that can be used as a reader, and then hook it up in pulumi-svmkit using something like this https://github.com/pulumi/pulumi-command/blob/master/provider/pkg/provider/util/util.go#L32

Did you have a second to check this out?  How did it look to you?

**Comment by Princeadxisrael** [comment]
Yeah I did check it out. Looks great for this use case. Seems to me that we are bypassing the filesystem.

**Comment by alexanderguy** [comment]
Yah exactly.  I think we can just create some buffers and do the reads right into whoever needs to consume things (e.g. pulumi)

**Comment by alexanderguy** [comment]
If you're on Telegram, message me @alxndrguy and I'll invite you to the `SVMKit Hackers` channel.

**Comment by Princeadxisrael** [comment]
I can't leave you a dm, error from not being a mutual contact. see if you could dm me instead @Aseneca

**Comment by alexanderguy** [comment]
Hey @Princeadxisrael I've started merging in initial support for streaming logs from the underlying scripts runner:

- https://github.com/abklabs/svmkit/blob/main/pkg/x/runner/deployer.go#L90
- https://github.com/abklabs/pulumi-svmkit/commit/85db42042fd814adb8fd4fdad9adc41266b4b61e#diff-199bc27f1bcd4fa080781c3cc247b50ce6c146b0576403d7606da1f85503d2f9R13

These should get released tomorrow.  Once those are in, I'd love to get your feedback on them.  I'm going to close this PR, and if you want to reopen with further changes to the new API, we can do that.

**Pull request closed without merging**
